# Generated by Django 4.2.8 on 2024-03-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_about_alter_music_name_and_more'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='music',
            field=models.ManyToManyField(to='music.music', verbose_name='Music'),
        ),
    ]
