# Generated by Django 4.2.8 on 2024-03-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='about of the music'),
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=126, verbose_name='name of the music'),
        ),
        migrations.AlterField(
            model_name='music',
            name='released_date',
            field=models.DateField(verbose_name='released_date of the music'),
        ),
    ]
