# Generated by Django 4.2.8 on 2024-03-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0002_alter_music_about_alter_music_name_and_more'),
        ('album', '0002_album_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=126, verbose_name='fullname of  Artist')),
                ('date_of_birth', models.DateField(verbose_name='birth of the Artist')),
                ('information', models.TextField(blank=True, null=True, verbose_name='information of th Artist')),
                ('photo', models.ImageField(upload_to='artist-photos/%Y/%m/%d', verbose_name='img Artist')),
                ('albums', models.ManyToManyField(to='album.album', verbose_name='Albums')),
                ('songs', models.ManyToManyField(to='music.music', verbose_name='musics')),
            ],
            options={
                'verbose_name': 'Arist',
                'verbose_name_plural': 'Artists',
            },
        ),
    ]
